ASP.NETSkola/Models/Student.cs
using System.ComponentModel;

namespace ASP.NETSkola.Models
{
    public class Student
    {
        public int Id { get; set; }
        [DisplayName("First Name")]
        public string? FirstName { get; set; }
        [DisplayName("Last Name")]
        public string? LastName { get; set; }
        [DisplayName("Date of Birth")]
        public DateTime DateOfBirth { get; set; }
    }
}

ASP.NETSkola/Controllers/FileUploadController.cs
using ASP.NETSkola.Models;
using ASP.NETSkola.Services;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using System.Xml;

namespace ASP.NETSkola.Controllers
{
    public class FileUploadController : Controller
    {
        StudentService studentService;

        public FileUploadController(StudentService studentService)
        {
            this.studentService = studentService;
        }

        public async Task<IActionResult> UploadAsync(IFormFile file)
        {
            if (file.Length > 0)
            {
                string filePath = Path.GetFullPath(file.FileName);
                using(var stream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                    stream.Close();
                    XmlDocument xmlDocument = new XmlDocument();
                    xmlDocument.Load(filePath);
                    XmlElement rootNode = xmlDocument.DocumentElement;
                    foreach (XmlNode node in rootNode.SelectNodes("/Students/Student"))
                    {
                        Student newStudent = new Student()
                        {
                            FirstName = node.ChildNodes[0].InnerText,
                            LastName = node.ChildNodes[1].InnerText,
                            DateOfBirth = DateTime.Parse(node.ChildNodes[2].InnerText, CultureInfo.CreateSpecificCulture("cs-CZ"))
                        };
                    await studentService.CreateStudentAsync(newStudent);
                    }
                }
                return RedirectToAction("Index", "Students");
            }
            return View("NotFound");
        }
    }
}

ASP.NETSkola/Controllers/StudentsController.cs
using ASP.NETSkola.Models;
using ASP.NETSkola.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ASP.NETSkola.Controllers
{
    [Authorize(Roles = "Teacher, Admin")]
    public class StudentsController : Controller
    {
        public StudentService service;

        public StudentsController(StudentService studentService)
        {
            this.service = studentService;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var allStudents = await service.GetAllAsync();
            return View(allStudents);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateAsync(Student student)
        {
            await service.CreateStudentAsync(student);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(int id)
        {
            var studentToEdit = await service.GetById(id);
            if (studentToEdit == null)
            {
                return View("NotFound");
            }
            return View(studentToEdit);
        }
        [HttpPost]
        public async Task<IActionResult> EditAsync(int id, [Bind("Id, FirstName, LastName, DateOfBirth")] Student student)
        {
            await service.UpdateAsync(student);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var studentToDelete = await service.GetById(id);
            if (studentToDelete == null)
            {
                return View("NotFound");
            }
            await service.DeleteAsync(studentToDelete);
            return RedirectToAction("Index");
        }
    }
}

ASP.NETSkola/Views/Students/Create.cshtml
@model Student
<form asp-controller="FileUpload" asp-action="Upload" enctype="multipart/form-data">
    <div class="mt-2">
    <input type="file" name="file"/>
    <input type="submit" value="Upload it!" />
    </div>
</form>
<form asp-action="Create">
    <div class="form-group mt-2">
    <label asp-for="@Model.FirstName"></label>
        <input type="text" asp-for="@Model.FirstName" class="form-control" />
    </div>
    <div class="form-group mt-2">
    <label asp-for="@Model.LastName"></label>
        <input type="text" asp-for="@Model.LastName" class="form-control" />
    </div>
    <div class="form-group mt-2">
    <label asp-for="@Model.DateOfBirth"></label>
        <input type="date" asp-for="@Model.DateOfBirth" class="form-control" />
    </div>
    <input class="btn btn-outline-success mt-2" type="submit" value="Create"/>
</form>

ASP.NETSkola/Views/Students/Edit.cshtml
@model Student
<form asp-action="Edit">
    <div class="form-group mt-2">
    <label asp-for="@Model.FirstName"></label>
        <input type="text" asp-for="@Model.FirstName" class="form-control" />
    </div>
    <div class="form-group mt-2">
    <label asp-for="@Model.LastName"></label>
        <input type="text" asp-for="@Model.LastName" class="form-control" />
    </div>
    <div class="form-group mt-2">
    <label asp-for="@Model.DateOfBirth"></label>
        <input type="date" asp-for="@Model.DateOfBirth" class="form-control" />
    </div>
    <input class="btn btn-outline-success mt-2" type="submit" value="Update student"/>
</form>

ASP.NETSkola/Views/Students/Index.cshtml
@model IEnumerable<Student>
@using System.Globalization

    <h3>List of registered students</h3>
    <a class="btn btn-outline-success mb-2" asp-action="Create">Add new student(s)</a>

@foreach(var student in Model)
{
    <div class="border border-1 border-primary p-2 rounded-3 mb-1">
    <h5>@student.FirstName @student.LastName</h5>
    <p>Id:@student.Id</p>
    @* <p>Date of birth: @student.DateOfBirth.ToShortDateString()</p> *@
    <p>Date of birth: @student.DateOfBirth.ToString("d", CultureInfo.CurrentCulture)</p>
    <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@student.Id">Update</a>
    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@student.Id">Delete</a>
    </div>
}